---
# file: roles/common/tasks/RedHat.yml

- name: Install common Redhat packages
  sudo: True
  yum: pkg={{ item }} state=present
  with_items:
    - git
    - wget 
    - curl 
    - rsync 
  when: ansible_os_family == 'Redhat'
  tags: common-redhat-packages 
