---
# file: laptops.yml

- hosts: laptops
  connection: local
  roles:
    - common
    - java 
    - maven 
    - { role: golang, golang_path: "/home/pinter/ext/golang", golang_path_user: "pinter" }
