---
# file: roles/jdk/tasks/Debian_alternatives.yml

- name: Inform the system where new jdk is located
  command: $item
  with_items:
    - update-alternatives --install /usr/bin/java java {{ jdk.installdir }}/jdk{{ jdk.version }}/bin/java 1
    - update-alternatives --install /usr/bin/javac javac {{ jdk.installdir }}/jdk{{ jdk.version }}/bin/javac 1 
    - update-alternatives --install /usr/bin/javaws javaws {{ jdk.installdir }}/jdk{{ jdk.version }}/jre/bin/javaws 1 
    - update-alternatives --install /usr/bin/javah javah {{ jdk.installdir }}/jdk{{ jdk.version }}/bin/javah 1
    - update-alternatives --install /usr/bin/jar jar {{ jdk.installdir }}/jdk{{ jdk.version }}/bin/jar 1 
  tags: jdk

- name: Inform the system that new jdk must be the default
  command: $item
  with_items:
    - update-alternatives --set java {{ jdk.installdir }}/jdk{{ jdk.version }}/bin/java 
    - update-alternatives --set javac {{ jdk.installdir }}/jdk{{ jdk.version }}/bin/javac 
    - update-alternatives --set javaws {{ jdk.installdir }}/jdk{{ jdk.version }}/jre/bin/javaws
    - update-alternatives --set javah {{ jdk.installdir }}/jdk{{ jdk.version }}/bin/javah
    - update-alternatives --set jar {{ jdk.installdir }}/jdk{{ jdk.version }}/bin/jar 
  tags: jdk
