---
# file: roles/java/defaults/main.yml 

#java.version.current:  
java:
  version:
    current: 1.7.0_45
    previous: 1.7.0_40

#java.installdir:  
  installdir: /usr/local/java 

#java.archive.jdk:  
  archive:
    jdk: jdk-7u45-linux-x64.tar.gz

#java.archive.jre:  
    jre: jre-7u45-linux-x64.tar.gz
