---
# file: roles/java/tasks/Debian.yml

- name: create a java directory
  file: path=${java_install_dir_Debian_${ansible_architecture}} owner=root group=root mode=0775 state=directory
  tags: jdk_extracted

- name: copy jdk${jvm_version} archive file
  copy: src=${jdk_archive_Debian_${ansible_architecture}} dest=${java_install_dir_Debian_${ansible_architecture}} mode=0664
  tags: jdk_extracted

- name: extract jdk${jvm_version} archive file
  action: command creates=${java_install_dir_Debian_${ansible_architecture}}/jdk${jvm_version} chdir=${java_install_dir_Debian_${ansible_architecture}} tar zxvf ${java_install_dir_Debian_${ansible_architecture}}/${jdk_archive_Debian_${ansible_architecture}} --owner=root
  register: ${jvm_version}_jdk_extracted
  tags: jdk_extracted

- name: install java alternatives
  action: command update-alternatives --install /usr/bin/java java ${java_install_dir_Debian_${ansible_architecture}}/jdk${jvm_version}/bin/java 1
  tags: java_alternatives 

- name: set java alternatives
  action: command update-alternatives --set java ${java_install_dir_Debian_${ansible_architecture}}/jdk${jvm_version}/bin/java
  tags: java_alternatives 

- name: install jar alternatives
  action: command update-alternatives --install /usr/bin/jar jar ${java_install_dir_Debian_${ansible_architecture}}/jdk${jvm_version}/bin/jar 1
  tags: java_alternatives 

- name: set jar alternatives
  action: command update-alternatives --set jar ${java_install_dir_Debian_${ansible_architecture}}/jdk${jvm_version}/bin/jar
  tags: java_alternatives 

- name: install javac alternatives
  action: command update-alternatives --install /usr/bin/javac javac ${java_install_dir_Debian_${ansible_architecture}}/jdk${jvm_version}/bin/javac 1
  tags: java_alternatives 

- name: set javac alternatives
  action: command update-alternatives --set javac ${java_install_dir_Debian_${ansible_architecture}}/jdk${jvm_version}/bin/javac
  tags: java_alternatives 

- name: install javaws alternatives
  action: command update-alternatives --install /usr/bin/javaws javaws ${java_install_dir_Debian_${ansible_architecture}}/jdk${jvm_version}/jre/bin/javaws 1
  tags: java_alternatives 

- name: set javaws alternatives
  action: command update-alternatives --set javaws ${java_install_dir_Debian_${ansible_architecture}}/jdk${jvm_version}/jre/bin/javaws
  tags: java_alternatives 

- name: create a java latest symlink
  file: src=${java_install_dir_Debian_${ansible_architecture}}/jdk${jvm_version} dest=${java_install_dir_Debian_${ansible_architecture}}/latest owner=root group=root state=link
  tags: java_profiledotd 

- name: Copy config $item 
  action: template src=etc_profiled_java_Debian_${ansible_architecture}.sh dest=/etc/profile.d/java.sh owner=root group=root mode=0644
  tags: java_profiledotd 

- name: cleanup jdk${jvm_version} archive file
  file: path=${java_install_dir_Debian_${ansible_architecture}}/${jdk_archive_Debian_${ansible_architecture}} state=absent
