---
# file: roles/java/tasks/Debian.yml

- name: create a java directory
  file: path=${java_install_dir_Debian_${ansible_architecture}} owner=root group=root mode=0775 state=directory
  tags: create-debian-java-dir

- name: copy jdk${jvm_version} archive file
  copy: src=${jdk_archive_Debian_${ansible_architecture}} dest=${java_install_dir_Debian_${ansible_architecture}} mode=0664
  tags: copy-debian-jdk 

- name: extract jdk${jvm_version} archive file
  action: command creates=${java_install_dir_Debian_${ansible_architecture}}/jdk${jvm_version} chdir=${java_install_dir_Debian_${ansible_architecture}} tar zxvf ${java_install_dir_Debian_${ansible_architecture}}/${jdk_archive_Debian_${ansible_architecture}} --owner=root
  register: ${jvm_version}_jdk_extracted

- name: copy jre${jvm_version} archive file
  copy: src=${jre_archive_Debian_${ansible_architecture}} dest=${java_install_dir_Debian_${ansible_architecture}} mode=0664
  tags: copy-debian-jre 

- name: extract jre${jvm_version} archive file
  action: command creates=${java_install_dir_Debian_${ansible_architecture}}/jre${jvm_version} chdir=${java_install_dir_Debian_${ansible_architecture}} tar zxvf ${java_install_dir_Debian_${ansible_architecture}}/${jre_archive_Debian_${ansible_architecture}} --owner=root
  register: ${jvm_version}_jre_extracted

- name: install java alternatives
  action: command update-alternatives --install /usr/bin/java java ${java_install_dir_Debian_${ansible_architecture}}/jre${jvm_version}/bin/java 1
  when_set: "${jvm_version}_jre_extracted"

- name: set java alternatives
  action: command update-alternatives --set java ${java_install_dir_Debian_${ansible_architecture}}/jre${jvm_version}/bin/java
  when_set: "${jvm_version}_jre_extracted"

- name: install jar alternatives
  action: command update-alternatives --install /usr/bin/jar jar ${java_install_dir_Debian_${ansible_architecture}}/jdk${jvm_version}/bin/jar 1
  when_set: "${jvm_version}_jdk_extracted"

- name: set jar alternatives
  action: command update-alternatives --set jar ${java_install_dir_Debian_${ansible_architecture}}/jdk${jvm_version}/bin/jar
  when_set: "${jvm_version}_jdk_extracted"

- name: install javac alternatives
  action: command update-alternatives --install /usr/bin/javac javac ${java_install_dir_Debian_${ansible_architecture}}/jdk${jvm_version}/bin/javac 1
  when_set: "${jvm_version}_jdk_extracted"

- name: set javac alternatives
  action: command update-alternatives --set javac ${java_install_dir_Debian_${ansible_architecture}}/jdk${jvm_version}/bin/javac
  when_set: "${jvm_version}_jdk_extracted"

- name: install javaws alternatives
  action: command update-alternatives --install /usr/bin/javaws javaws ${java_install_dir_Debian_${ansible_architecture}}/jre${jvm_version}/bin/javaws 1
  when_set: "${jvm_version}_jre_extracted"

- name: set javaws alternatives
  action: command update-alternatives --set javaws ${java_install_dir_Debian_${ansible_architecture}}/jre${jvm_version}/bin/javaws
  when_set: "${jvm_version}_jre_extracted"

- name: Copy config $item 
  action: template src=etc_profiled_java_Debian_${ansible_architecture}.sh dest=/etc/profile.d/java.sh owner=root group=root mode=0644
  when_set: "${jvm_version}_jre_extracted"
