---
# file: roles/java/tasks/RedHat.yml

- name: Create a RedHat java directory
  file: path={{ java_install_dir_RedHat_x86_64 }} owner=root group=root mode=0775 state=directory
  tags: jdk 

- name: Copy jdk{{ jvm_version }} rpm file
  copy: src={{ jdk_archive_RedHat_x86_64 }} dest={{ java_install_dir_RedHat_x86_64 }} mode=0664
  tags: jdk 

- name: Install jdk{{ jvm_version }} rpm file
  action: shell yum -y --nogpgcheck localinstall {{ java_install_dir_RedHat_x86_64 }}/{{ jdk_archive_RedHat_x86_64 }} 
  tags: jdk 

- name: Install java alternatives
  action: command /usr/sbin/alternatives --install /usr/bin/java java {{ java_install_dir_RedHat_x86_64 }}/jdk{{ jvm_version }}/bin/java 20000 
  tags: jdk 

- name: Set java alternatives
  action: command /usr/sbin/alternatives --set java {{ java_install_dir_RedHat_x86_64 }}/jdk{{ jvm_version }}/bin/java
  tags: jdk 

- name: Install jar alternatives
  action: command /usr/sbin/alternatives --install /usr/bin/jar jar {{ java_install_dir_RedHat_x86_64 }}/jdk{{ jvm_version }}/bin/jar 20000 
  tags: jdk 

- name: Set jar alternatives
  action: command /usr/sbin/alternatives --set jar {{ java_install_dir_RedHat_x86_64 }}/jdk{{ jvm_version }}/bin/jar
  tags: jdk 

- name: Install javac alternatives
  action: command /usr/sbin/alternatives --install /usr/bin/javac javac {{ java_install_dir_RedHat_x86_64 }}/jdk{{ jvm_version }}/bin/javac 20000 
  tags: jdk 

- name: Set javac alternatives
  action: command /usr/sbin/alternatives --set javac {{ java_install_dir_RedHat_x86_64 }}/jdk{{ jvm_version }}/bin/javac
  tags: jdk 

- name: Create a java latest symlink
  file: src={{ java_install_dir_RedHat_x86_64 }}/jdk{{ jvm_version }} dest={{ java_install_dir_RedHat_x86_64 }}/latest owner=root group=root state=link
  tags: jdk 

- name: Copy config $item 
  action: template src=etc_profiled_java_RedHat_x86_64.sh.j2 dest=/etc/profile.d/java.sh owner=root group=root mode=0644
  tags: jdk 

- name: Cleanup RedHat jdk{{ jvm_version }} archive file
  file: path={{ java_install_dir_RedHat_x86_64 }}/{{ jdk_archive_RedHat_x86_64 }} state=absent
  tags: jdk 
