---
# file: roles/java/tasks/RedHat.yml

- name: Create a RedHat java directory
  file: path={{ java.installdir }} owner=root group=root mode=0775 state=directory
  tags: jdk 

- name: Copy jdk{{ java.version }} rpm file
  copy: src={{ java.archive.jdk }} dest={{ java.installdir }} mode=0664
  tags: jdk 

- name: Install jdk{{ java.version }} rpm file
  action: shell yum -y --nogpgcheck localinstall {{ java.installdir }}/{{ java.archive.jdk }} 
  tags: jdk 

- name: Install java alternatives
  action: command /usr/sbin/alternatives --install /usr/bin/java java {{ java.installdir }}/jdk{{ java.version }}/bin/java 20000 
  tags: jdk 

- name: Set java alternatives
  action: command /usr/sbin/alternatives --set java {{ java.installdir }}/jdk{{ java.version }}/bin/java
  tags: jdk 

- name: Install jar alternatives
  action: command /usr/sbin/alternatives --install /usr/bin/jar jar {{ java.installdir }}/jdk{{ java.version }}/bin/jar 20000 
  tags: jdk 

- name: Set jar alternatives
  action: command /usr/sbin/alternatives --set jar {{ java.installdir }}/jdk{{ java.version }}/bin/jar
  tags: jdk 

- name: Install javac alternatives
  action: command /usr/sbin/alternatives --install /usr/bin/javac javac {{ java.installdir }}/jdk{{ java.version }}/bin/javac 20000 
  tags: jdk 

- name: Set javac alternatives
  action: command /usr/sbin/alternatives --set javac {{ java.installdir }}/jdk{{ java.version }}/bin/javac
  tags: jdk 

- name: Create a java latest symlink
  file: src={{ java.installdir }}/jdk{{ java.version }} dest={{ java.installdir }}/latest owner=root group=root state=link
  tags: jdk 

- name: Copy config to /etc/profile.d/java.sh 
  action: template src=etc_profiled_java.sh.j2 dest=/etc/profile.d/java.sh owner=root group=root mode=0644
  tags: jdk 

- name: Cleanup RedHat jdk{{ java.version }} archive file
  file: path={{ java.installdir }}/{{ java.archive.jdk }} state=absent
  tags: jdk 
