---
# file: roles/packer/tasks/main.yml

- name: Is packer currently installed?
  shell: "[ -d {{ packer_install_dir }}/{{ packer_version }} ] && echo 'Found' || echo ''"
  register: packer_installed
  tags: packer

- name: Create packer install directory
  file: path={{ packer_install_dir }} owner=root group=root mode=0775 state=directory
  when: (not packer_installed.stdout)
  tags: packer

- name: Create packer version directory
  file: path={{ packer_install_dir }}/{{ packer_version }} owner=root group=root mode=0775 state=directory
  when: (not packer_installed.stdout)
  tags: packer

- name: Download packer binary archive file
  get_url: dest={{ packer_install_dir }}/{{ packer_version }}/{{ packer_download_filename }} url={{ packer_download_url }}
  when: (not packer_installed.stdout)
  tags: packer

- name: Extract packer archive file
  unarchive: src={{ packer_install_dir }}/{{ packer_version }}/{{ packer_download_filename }} dest={{ packer_install_dir }}/{{ packer_version }}
  when: (not packer_installed.stdout)
  tags: packer

- name: Create a packer latest symlink
  file: src={{ packer_install_dir }}/{{ packer_version }} dest={{ packer_install_dir }}/latest owner=root group=root state=link
  when: (not packer_installed.stdout)
  tags: packer

- name: Copy config to /etc/profile.d/packer.sh
  action: template src=etc_profiled_packer.sh.j2 dest=/etc/profile.d/packer.sh owner=root group=root mode=0644
  when: (not packer_installed.stdout)
  tags: packer

- name: Cleanup packer archive file
  file: path={{ packer_install_dir }}/{{ packer_version }}/{{ packer_download_filename }} state=absent
  when: (not packer_installed.stdout)
  tags: packer
