---
# file: roles/golang/vars/main.yml 

golang_major_version: 1 
golang_minor_version: 1.1.1
golang_base_url: https://go.googlecode.com/files/
golang_download_file_x86_64: go${golang_minor_version}.linux-amd64.tar.gz
golang_download_url_x86_64: ${golang_base_url}${golang_download_file_x86_64} 
golang_install_dir: /usr/local

# NOTE: golang_path & golang_path_user can be set at the playbook/vars level to define the GOPATH env variable
# GOPATH is set via templates/etc_profiled_go.sh.j2
