---
# file: roles/maven/tasks/main.yml

- name: Is maven currently installed?
  shell: "[ -d {{ maven.install_dir }}/maven ] && echo 'Found' || echo ''"
  register: mvn_installed
  tags: maven 

- name: Create a maven directory
  file: path={{ maven.install_dir }} owner=root group=root state=directory
  when: (not mvn_installed.stdout)
  tags: maven

- name: Is current version (ie {{ maven.version }}) of maven already installed?
  shell: "{{ maven.install_dir }}/maven/bin/mvn -version | grep 'Apache Maven {{ maven.version }}'"
  when: mvn_installed.stdout
  register: mvn_version_installed
  changed_when: "mvn_version_installed.rc == 1"
  ignore_errors: True
  tags: maven
  
- name: Download maven 
  get_url: dest={{ maven.install_dir }}/apache-maven-{{ maven.version }}-bin.tar.gz url={{ maven.download_url }}
  when: (not mvn_installed.stdout) or (not mvn_version_installed.stdout)
  tags: maven

- name: Extract maven archive file
  action: command creates={{ maven.install_dir }}/apache-maven-{{ maven.version }} chdir={{ maven.install_dir }} tar zxvf {{ maven.install_dir }}/apache-maven-{{ maven.version }}-bin.tar.gz --owner=root
  when: (not mvn_installed.stdout) or (not mvn_version_installed.stdout)
  tags: maven

- name: Create a maven symlink
  file: src={{ maven.install_dir }}/apache-maven-{{ maven.version }} dest={{ maven.install_dir }}/maven owner=root group=root state=link
  when: (not mvn_installed.stdout) or (not mvn_version_installed.stdout)
  tags: maven

- name: Copy config maven.sh 
  action: template src=etc_profiled_maven.sh.j2 dest=/etc/profile.d/maven.sh owner=root group=root mode=0644
  when: (not mvn_installed.stdout) or (not mvn_version_installed.stdout)
  tags: maven

- name: Cleanup maven {{ maven.version }} archive file 
  file: path={{ maven.install_dir }}/apache-maven-{{ maven.version }}-bin.tar.gz state=absent
  when: (not mvn_installed.stdout) or (not mvn_version_installed.stdout)
  tags: maven
